version: "3"

services:
  python_aiokafka:
    build:
      context: python_aiokafka
    volumes:
      - ./python_aiokafka:/code
      - ~/.ssh:/home/app/.ssh
    depends_on:
      jaeger:
        condition: service_started
      redpanda:
        condition: service_healthy
    environment:
      OPENTELEMETRY_ENDPOINT: http://jaeger:55681/v1/traces
      SOURCE: one
      DESTINATION: two

  elixir_brod:
    build:
      context: elixir_brod
    volumes:
      - ./elixir_brod:/code
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      SOURCE: two
      DESTINATION: three

  rust_rdkafka:
    build: rust_rdkafka
    container_name: rust_rdkafka
    hostname: rust_rdkafka
    environment:
      CARGO_TARGET_DIR: "target-docker"
      SOURCE: three
      DESTINATION: one
      RUST_LOG: info
    volumes:
      - ".:/code"
    working_dir: "/code/rust_rdkafka"
    depends_on:
      redpanda:
        condition: service_healthy
      jaeger:
        condition: service_started

  redpanda:
    image: redpandadata/redpanda:v22.3.20
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --memory 1G
      - --reserve-memory 0M
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://kafka:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:9644/v1/status/ready"]
      interval: 1s
      timeout: 1s
      retries: 3
    networks:
      default:
        aliases:
          - kafka
          - schema-registry
    depends_on:
      - console
    restart: unless-stopped

  console:
    image: redpandadata/console:v2.2.4
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
    ports:
      - "8080:8080"
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - 16686:16686
      - 55681:55681
    environment:
      COLLECTOR_OTLP_ENABLED: true
      COLLECTOR_OTLP_HTTP_HOST_PORT: 55681

volumes:
  redpanda-data:
